export const MatrixActions = {
	ADD_ROW: "ADD_ROW",
	REMOVE_ROW: "REMOVE_ROW",
	CREATE_MATRIX: "CREATE_MATRIX",
	SET_SETTINGS: "SET_SETTINGS",
	SET_CLOSEST_ID: "SET_CLOSEST_ID",
	INCREASE_AMOUNT: "INCREASE_AMOUNT",
	CLEAR_CLOSEST_ID: "CLEAR_CLOSEST_ID",
 };